---
- name: Add user to group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  loop: '{{ microk8s_users }}'

- name: Create .kube folder for the user
  become: false
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0750
  loop: "{{ microk8s_users }}"

- name: Create kubectl config
  become: true
  changed_when: false
  ansible.builtin.shell: microk8s config > /home/{{ item }}/.kube/config
  args:
    executable: /bin/bash
  loop: "{{ microk8s_users }}"

- name: Reaffirm permission on files
  become: true
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    recurse: yes
  loop: "{{ microk8s_users }}"

- name: Add helm repository to user
  become: true
  become_user: "{{ item.0 }}"
  kubernetes.core.helm_repository: 
    name: "{{ item.1.name }}"
    repo_url: "{{ item.1.url }}"
  with_nested:
    - "{{ microk8s_users }}"
    - "{{ helm3_repositories }}"
  when: 
    - microk8s_plugins.helm3
    - inventory_hostname in groups[microk8s_group_ha]

# - name: Update helm repos
#   become: true
#   become_user: "{{ item }}"
#   ansible.builtin.shell: helm repo update
#   args:
#     executable: /bin/bash
#   changed_when: true
#   loop: "{{ microk8s_users }}"
#   when: microk8s_plugins.helm3
