---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Configure users
  ansible.builtin.include_tasks: configure-groups.yml
  when: "microk8s_users is defined and microk8s_users not in ([], None, '', omit)"

- name: Configure single node addons
  ansible.builtin.include_tasks: addons.yml
  when: not microk8s_enable_ha

- name: Configure High Availability
  ansible.builtin.include_tasks: configure-ha.yml
  when: "microk8s_enable_ha"

- name: Configure workers
  ansible.builtin.include_tasks: configure-workers.yml
  when: "groups[microk8s_group_workers]|length>0"
